/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RefreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ChangePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListUsers"];
        put?: never;
        post: operations["CreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["UpdateUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ResetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListEmployees"];
        put?: never;
        post: operations["CreateEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetEmployee"];
        put: operations["UpdateEmployee"];
        post?: never;
        delete: operations["ArchiveEmployee"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetGrades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{trackId}/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMatrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grade-role-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetGradeRoleRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessment-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListSessions"];
        put?: never;
        post: operations["CreateSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessment-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSession"];
        put: operations["UpdateSession"];
        post?: never;
        delete: operations["DeleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessment-sessions/{id}/survey-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSurveyPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessment-sessions/{id}/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LaunchSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessment-sessions/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CancelSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessment-sessions/{id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AddParticipant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessment-sessions/{id}/participants/{participantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["RemoveParticipant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessment-sessions/{id}/participants/{participantId}/reissue-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReissueParticipantLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetSurvey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/{token}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["SaveSurveyDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surveys/{token}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SubmitSurvey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddParticipantRequest: {
            fullName: string;
            email: string;
            role: components["schemas"]["EvaluatorRole"];
        };
        AddParticipantResult: {
            participant: components["schemas"]["ParticipantDto"];
            link: null | components["schemas"]["ParticipantLinkDto"];
        };
        AuthResponse: {
            accessToken: string;
            /** Format: date-time */
            expiresAtUtc: string;
            user: components["schemas"]["AuthUser"];
        };
        AuthUser: {
            /** Format: uuid */
            id: string;
            email: string;
            fullName: string;
            role: string;
            mustChangePassword: boolean;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        CompetencyGroupDto: {
            /** Format: uuid */
            id: string;
            name: string;
            description: null | string;
            /** Format: int32 */
            order: number;
            indicators: components["schemas"]["IndicatorDto"][];
        };
        CreateEmployeeCommand: {
            fullName: string;
            email: string;
            /** Format: uuid */
            trackId: string;
            /** Format: uuid */
            gradeId: string;
            /** Format: uuid */
            managerUserId: null | string;
        };
        CreateSessionCommand: {
            /** Format: uuid */
            employeeId: string;
            type: components["schemas"]["SessionType"];
            /** Format: date-time */
            deadlineAtUtc: string;
            participants: components["schemas"]["NewParticipant"][];
        };
        CreateUserCommand: {
            email: string;
            fullName: string;
            role: string;
            password: string;
        };
        EmployeeDto: {
            /** Format: uuid */
            id: string;
            fullName: string;
            email: string;
            /** Format: uuid */
            trackId: string;
            trackName: string;
            /** Format: uuid */
            gradeId: string;
            gradeCode: string;
            gradeName: string;
            /** Format: uuid */
            managerUserId: string;
            managerName: string;
            isActive: boolean;
        };
        /** @enum {unknown} */
        EvaluatorRole: "Self" | "Peer" | "TeamLead" | "Manager" | "Rck" | "ItLeader";
        GradeDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** Format: int32 */
            order: number;
        };
        GradeRoleRuleDto: {
            /** Format: uuid */
            gradeId: string;
            gradeCode: string;
            role: components["schemas"]["EvaluatorRole"];
            /** Format: int32 */
            minCount: number;
            /** Format: int32 */
            maxCount: number;
        };
        IndicatorDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gradeId: string;
            text: string;
            /** Format: int32 */
            order: number;
        };
        /** @enum {unknown} */
        LevelKind: "Current" | "Target";
        LoginRequest: {
            email: string;
            password: string;
        };
        MatrixDto: {
            track: components["schemas"]["TrackDto"];
            grades: components["schemas"]["GradeDto"][];
            groups: components["schemas"]["CompetencyGroupDto"][];
        };
        NewParticipant: {
            fullName: string;
            email: string;
            role: components["schemas"]["EvaluatorRole"];
        };
        ParticipantDto: {
            /** Format: uuid */
            id: string;
            fullName: string;
            email: string;
            role: components["schemas"]["EvaluatorRole"];
            status: components["schemas"]["ParticipantStatus"];
            /** Format: date-time */
            tokenIssuedAtUtc: null | string;
            /** Format: date-time */
            firstOpenedAtUtc: null | string;
            /** Format: date-time */
            submittedAtUtc: null | string;
        };
        ParticipantLinkDto: {
            /** Format: uuid */
            participantId: string;
            fullName: string;
            role: components["schemas"]["EvaluatorRole"];
            url: string;
        };
        /** @enum {unknown} */
        ParticipantStatus: "Pending" | "InProgress" | "Submitted" | "Removed";
        PreviewGroupDto: {
            name: string;
            indicators: components["schemas"]["PreviewIndicatorDto"][];
        };
        PreviewIndicatorDto: {
            text: string;
            gradeCode: string;
            levelKind: components["schemas"]["LevelKind"];
        };
        ResetPasswordRequest: {
            newPassword: string;
        };
        RoleRequirementDto: {
            role: components["schemas"]["EvaluatorRole"];
            /** Format: int32 */
            minCount: number;
            /** Format: int32 */
            maxCount: number;
            /** Format: int32 */
            count: number;
            isSatisfied: boolean;
        };
        SessionDetailsDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            employeeId: string;
            employeeName: string;
            employeeEmail: string;
            trackName: string;
            type: components["schemas"]["SessionType"];
            currentGrade: components["schemas"]["GradeDto"];
            targetGrade: null | components["schemas"]["GradeDto"];
            status: components["schemas"]["SessionStatus"];
            /** Format: date-time */
            deadlineAtUtc: string;
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: date-time */
            launchedAtUtc: null | string;
            /** Format: date-time */
            completedAtUtc: null | string;
            /** Format: date-time */
            closedAtUtc: null | string;
            /** Format: uuid */
            ownerUserId: string;
            ownerName: string;
            /** Format: int32 */
            indicatorCount: number;
            participants: components["schemas"]["ParticipantDto"][];
            roleRequirements: components["schemas"]["RoleRequirementDto"][];
        };
        SessionListItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            employeeId: string;
            employeeName: string;
            type: components["schemas"]["SessionType"];
            currentGradeCode: string;
            targetGradeCode: null | string;
            status: components["schemas"]["SessionStatus"];
            /** Format: date-time */
            deadlineAtUtc: string;
            /** Format: int32 */
            participantsTotal: number;
            /** Format: int32 */
            participantsSubmitted: number;
            /** Format: uuid */
            ownerUserId: string;
            ownerName: string;
            /** Format: date-time */
            createdAtUtc: string;
        };
        /** @enum {unknown} */
        SessionStatus: "Draft" | "InProgress" | "Overdue" | "AwaitingDecision" | "Closed" | "Cancelled";
        /** @enum {unknown} */
        SessionType: "Transition" | "Confirmation";
        SurveyAnswerDto: {
            /** Format: uuid */
            indicatorId: string;
            /** Format: int32 */
            score: null | number;
            notApplicable: boolean;
            comment: null | string;
        };
        SurveyAnswersRequest: {
            answers: components["schemas"]["SurveyAnswerDto"][];
        };
        SurveyDto: {
            state: components["schemas"]["SurveyState"];
            employeeName: string;
            respondentName: string;
            role: components["schemas"]["EvaluatorRole"];
            /** Format: date-time */
            deadlineAtUtc: string;
            groups: components["schemas"]["SurveyGroupDto"][];
            answers: components["schemas"]["SurveyAnswerDto"][];
        };
        SurveyGroupDto: {
            name: string;
            indicators: components["schemas"]["SurveyIndicatorDto"][];
        };
        SurveyIndicatorDto: {
            /** Format: uuid */
            id: string;
            text: string;
        };
        SurveyPreviewDto: {
            /** Format: int32 */
            indicatorCount: number;
            groups: components["schemas"]["PreviewGroupDto"][];
        };
        /** @enum {unknown} */
        SurveyState: "Open" | "Submitted" | "Closed";
        TrackDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            isActive: boolean;
        };
        UpdateEmployeeRequest: {
            fullName: string;
            email: string;
            /** Format: uuid */
            trackId: string;
            /** Format: uuid */
            gradeId: string;
            /** Format: uuid */
            managerUserId: null | string;
            isActive: boolean;
        };
        UpdateSessionRequest: {
            type: components["schemas"]["SessionType"];
            /** Format: date-time */
            deadlineAtUtc: string;
        };
        UpdateUserRequest: {
            fullName: string;
            role: string;
            isActive: boolean;
        };
        UserDto: {
            /** Format: uuid */
            id: string;
            email: string;
            fullName: string;
            role: string;
            isActive: boolean;
            mustChangePassword: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    RefreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChangePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
        };
    };
    ListUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"][];
                };
            };
        };
    };
    CreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserCommand"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    UpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    ResetUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListEmployees: {
        parameters: {
            query?: {
                search?: string;
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDto"][];
                };
            };
        };
    };
    CreateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeCommand"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDto"];
                };
            };
        };
    };
    GetEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDto"];
                };
            };
        };
    };
    UpdateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDto"];
                };
            };
        };
    };
    ArchiveEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetTracks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackDto"][];
                };
            };
        };
    };
    GetGrades: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeDto"][];
                };
            };
        };
    };
    GetMatrix: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trackId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatrixDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetGradeRoleRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeRoleRuleDto"][];
                };
            };
        };
    };
    ListSessions: {
        parameters: {
            query?: {
                status?: components["schemas"]["SessionStatus"];
                employeeId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListItemDto"][];
                };
            };
        };
    };
    CreateSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionCommand"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailsDto"];
                };
            };
        };
    };
    GetSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailsDto"];
                };
            };
        };
    };
    UpdateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailsDto"];
                };
            };
        };
    };
    DeleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetSurveyPreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyPreviewDto"];
                };
            };
        };
    };
    LaunchSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantLinkDto"][];
                };
            };
        };
    };
    CancelSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AddParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddParticipantRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddParticipantResult"];
                };
            };
        };
    };
    RemoveParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                participantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReissueParticipantLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                participantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantLinkDto"];
                };
            };
        };
    };
    GetSurvey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyDto"];
                };
            };
        };
    };
    SaveSurveyDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SurveyAnswersRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SubmitSurvey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SurveyAnswersRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
