// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReviewPlatform.Infrastructure.Persistence;

#nullable disable

namespace ReviewPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929104724_InitialMatrix")]
    partial class InitialMatrix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReviewPlatform.Domain.Matrix.CompetencyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.HasKey("Id")
                        .HasName("pk_competency_groups");

                    b.HasIndex("TrackId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_competency_groups_track_id_name");

                    b.ToTable("competency_groups", (string)null);
                });

            modelBuilder.Entity("ReviewPlatform.Domain.Matrix.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id")
                        .HasName("pk_grades");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_grades_code");

                    b.HasIndex("Order")
                        .IsUnique()
                        .HasDatabaseName("ix_grades_order");

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("ReviewPlatform.Domain.Matrix.GradeRoleRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_id");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_count");

                    b.Property<int>("MinCount")
                        .HasColumnType("integer")
                        .HasColumnName("min_count");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_grade_role_rules");

                    b.HasIndex("GradeId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_grade_role_rules_grade_id_role");

                    b.ToTable("grade_role_rules", (string)null);
                });

            modelBuilder.Entity("ReviewPlatform.Domain.Matrix.Indicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_indicators");

                    b.HasIndex("GradeId")
                        .HasDatabaseName("ix_indicators_grade_id");

                    b.HasIndex("GroupId", "GradeId", "Text")
                        .IsUnique()
                        .HasDatabaseName("ix_indicators_group_id_grade_id_text")
                        .HasFilter("NOT is_archived");

                    b.ToTable("indicators", (string)null);
                });

            modelBuilder.Entity("ReviewPlatform.Domain.Matrix.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tracks");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tracks_code");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("ReviewPlatform.Domain.Matrix.CompetencyGroup", b =>
                {
                    b.HasOne("ReviewPlatform.Domain.Matrix.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competency_groups_tracks_track_id");
                });

            modelBuilder.Entity("ReviewPlatform.Domain.Matrix.GradeRoleRule", b =>
                {
                    b.HasOne("ReviewPlatform.Domain.Matrix.Grade", null)
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grade_role_rules_grades_grade_id");
                });

            modelBuilder.Entity("ReviewPlatform.Domain.Matrix.Indicator", b =>
                {
                    b.HasOne("ReviewPlatform.Domain.Matrix.Grade", null)
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_indicators_grades_grade_id");

                    b.HasOne("ReviewPlatform.Domain.Matrix.CompetencyGroup", null)
                        .WithMany("Indicators")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_indicators_competency_groups_group_id");
                });

            modelBuilder.Entity("ReviewPlatform.Domain.Matrix.CompetencyGroup", b =>
                {
                    b.Navigation("Indicators");
                });
#pragma warning restore 612, 618
        }
    }
}
